development: &non_production_settings
  site_url: http://localhost:3000
  site_name: FeedMatcher
  footer: Copyright ©2008 FeedMatcher
  admin_email: markmediadude@gmail.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: STAGING - FeedMatcher
  footer: Copyright ©2008 FeedMatcher
  admin_email: bort@bort.com  
  
production:
  site_url: http://feedmatcher.com
  site_name:  FeedMatcher
  footer: Copyright ©2008 FeedMatcher
  admin_email: markmediadude@gmail.com
